CREATE TABLE hp_storage (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  storage_key VARCHAR(64) NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  storage_type VARCHAR(16) NOT NULL COMMENT 'LOCAL|S3',
  endpoint VARCHAR(256) NULL,
  region VARCHAR(64) NULL,
  bucket VARCHAR(128) NULL,
  prefix VARCHAR(256) NULL,
  access_key_enc VARCHAR(1024) NULL,
  secret_key_enc VARCHAR(1024) NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_storage_key (storage_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
